#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += cypress-touchkey.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += issp_driver_routines.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += issp_main.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += issp_routines.o
